version: 2

sources:
  - name: raw         # schema name in your warehouse
    
    database: Airbnb
    tables:
      - name: emp    # table or file name in Snowflake
        description: "emp data from CRM"
      - name: host_list
        identifier: host_list
        description: "host list data from Airbnb"
      - name: host
        identifier: raw_hosts
      - name: listing
        identifier: raw_listings
      - name: raw_reviews
        identifier: raw_reviews
  - name: ECOMMERCE_raw
    schema: raw
    database: ECOMMERCE
    tables:
      - name: tbl_customer
        identifier: tbl_cust_raw
      - name: tbl_order
        identifier: raw_order
      - name: tbl_cust
        identifier: tbl_customer   # optional if name = identifier
      - name: tbl_ord
        identifier: tbl_order
    
